version: 2.1

orbs:
  releaser: puwnz/releaser@0.0.3

x-common: &x-common-php
  docker:
    - image: php:8.1-fpm-alpine3.20
      environment:
        APP_ENV: test
  working_directory: /var/www/app

jobs:
  prepare:
    <<: *x-common-php
    steps:
      - run:
            name: Install GIT
            command: |
                apk add --update git composer openssh-client
      - checkout
      - restore_cache:
          key: composer-{{ checksum "/var/www/app/composer.json" }}
      - run:
          name: install
          command: |
            composer install --no-scripts
            php -d memory_limit=-1 $(which composer) require friendsofphp/php-cs-fixer=^3.0 --no-scripts --dev
      - persist_to_workspace:
          root: /var/www/app/
          paths:
            - ./*
      - save_cache:
          key: composer-{{ checksum "/var/www/app/composer.json" }}
          paths: /var/www/app/vendor/
  tests:
    <<: *x-common-php
    steps:
      - attach_workspace:
          at: /var/www/app/
      - run:
          name: PHP Unit
          command: |
            vendor/bin/phpunit
          working_directory: /var/www/app/
  php-cs:
    <<: *x-common-php
    steps:
      - attach_workspace:
          at: /var/www/app/
      - run:
          name: PHP CS Fixer
          command: |
            vendor/bin/php-cs-fixer fix --dry-run --diff  --allow-risky=yes
          working_directory: /var/www/app/

workflows:
  version: 2
  push:
    jobs:
      - prepare
      - tests:
          requires:
            - prepare
      - php-cs:
          requires:
            - prepare
      - approval:
          type: approval
          requires:
            - tests
            - php-cs
          filters:
            branches:
              only:
                - /hotfix\/.*/
                - /release\/.*/
      - releaser/create_patch_tag:
          requires:
            - approval
          filters:
            branches:
              only:
                - /hotfix.*/
      - releaser/create_minor_tag:
          requires:
            - approval
          filters:
            branches:
              only:
                - /release.*/
